apiVersion: v1
kind: Service
metadata:
  name: healthcare-fastapi-service
spec:
  type: NodePort
  selector:
    app: healthcare-fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003  # Exposes FastAPI on this port
